name: Deploy to Hugging Face Spaces

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build with Vite
        run: npm run build
        env:
          VITE_BASE: /
      
      - name: Deploy to Hugging Face Spaces
        uses: huggingface/huggingface_hub@v0.1.0
        with:
          repo-type: space
          repo-id: CHKIM79/ai-automation-system
          space-sdk: static
          space-hardware: cpu-basic
          space-settings: |
            title: AI Automation System
            emoji: 🤖
            colorFrom: blue
            colorTo: purple
            sdk: static
            pinned: false
            license: mit
          path: dist
        env:
          HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}